development:
  adapter: postgresql
  encoding: utf8
  database: my_db24_name
  username: postgres
  password: root

production: 
  adapter: postgresql
  encoding: utf8
  database: my_db24_name
  username: postgres
  password: root